### ISSUE TITLE
No keyslots found

### ISSUE THREAD

**Issue by HellGL** [billyhulbert/XvddKeyslotUtil#1]
Hi,
when do I need to start the tool to find the keyslots? I installed a simple game and I can see the disk files in the MSIXVC directory but when I run the tool it does not find any keyslots: 

`\repos\XvddKeyslotUtil\bin\x64\Release>XvddKeyslotUtil.exe -o d:\tmp\cik -d d:\tmp\Kernel-Bridge\Kernel-Bridge.sys`
`[+] Checking if running with elevated privileges...`
`[+] CIK output path: "d:\\tmp\\cik"`
`[+] Kernel Bridge driver path: d:\tmp\Kernel-Bridge\Kernel-Bridge.sys`
`[+] Ensuring previous driver instance is removed...`
`[+] Installing Kernel-Bridge driver...`
`[+] Opening Kernel-Bridge handle...`
`[+] Getting xvdd.sysbase address...`
`[+] Fetching GUID slot table...`
`[+] Found 0 GUID slots!`
`[+] Fetching keyslot table...`
`[*] Keyslots:`

Any idea?

**Comment by billyhulbert** [comment]
Hello,

The issue is likely due to the project being outdated so the addresses may need to be adjusted. There is also a possibility that Microsoft have completely changed the way they store the keys. I may take a look soon to determine what's up with it though.

**Comment by billyhulbert** [comment]
I've pushed a rushed fix that should fix the problem. It was simply needing a little update. Let me know if this version works for you.

**Comment by HellGL** [comment]
Works like charm! Thank you verry much!
