### ISSUE TITLE
Failed to install Kernel-Bridge driver!

### ISSUE THREAD

**Issue by TempleOfHorus** [billyhulbert/XvddKeyslotUtil#10]
![obrázok](https://user-images.githubusercontent.com/60355056/219120121-68d04156-75f8-486f-9b09-7ee1d3a62280.png)
Any help ?

**Comment by billyhulbert** [comment]
Are you in Test Mode on Windows? You will need to enable it by doing the following:
```
bcdedit.exe /set loadoptions DISABLE_INTEGRITY_CHECKS
bcdedit.exe /set TESTSIGNING ON
```

You may also run into an issue afterwards as it's not been updated. Also, be sure to disable Test Mode/Test Signing after immediately and avoid running any anti-cheat based games as this project did false-flag BattlEye previously.

**Comment by TempleOfHorus** [comment]
![1](https://user-images.githubusercontent.com/60355056/219873563-ac8ed9d9-8792-4104-aad7-484acf65aa81.jpg)
Still doesn't work for some reason :/

**Comment by billyhulbert** [comment]
I recommend checking out: https://github.com/LukeFZ/CikExtractor
