### ISSUE TITLE
Keys are not matching?

### ISSUE THREAD

**Issue by DeBroin** [billyhulbert/XvddKeyslotUtil#2]
Hello!

I noticed that in issue #1 there was mention of changed offsets for newer Windows builds.
I was wondering if the offsets might've changed again?
With the initial release, I'm getting 99 keys, with the updated one 96. However, none of these keys seem to match what I'm looking for, i.e. the guid that xvdtool is telling me it should be.
Could you perhaps have a look, if it's not too much bother?

Many thanks!

**Comment by tuxuser** [comment]
Fixed with PR #6 - Version 1.0.0
