### ISSUE TITLE
Kernel-Bridge driver loading broken since KB5004237 (July 13, 2021)

### ISSUE THREAD

**Issue by tuxuser** [billyhulbert/XvddKeyslotUtil#8]
Apparently, as mentioned on [Windows-Kernel-Explorer](https://github.com/AxtMueller/Windows-Kernel-Explorer) repo, Microsoft blacklisted the certificate authority that was used to sign the [Kernel-Bridge](https://github.com/HoShiMin/Kernel-Bridge) driver with security update [KB5004237](https://support.microsoft.com/en-us/topic/july-13-2021-kb5004237-os-builds-19041-1110-19042-1110-and-19043-1110-ae798d3c-3de3-4c1f-b9d9-7391b71da889).

A possible workaround could be to enable **TEST MODE** in Windows and self-sign the driver. No instructions for that are provided here tho.

Alternative: Drink tea and wait for a new signed driver, provided by either **Windows-Kernel-Explorer** or **Kernel-Bridge** itself. Once such is available, a new release of XvddKeyslotUtil will be created.

## Current symptom

```
[+] Installing Kernel-Bridge driver...
[-] Failed to install Kernel-Bridge driver!
Last error: -2146762484
```

> HRESULT: 0x800B010C (-2146762484)
> A certificate was explicitly revoked by its issuer

**Comment by Cuu9Dine** [comment]
Tried in test mode already but didn't work. Seem like we have to wait for new kernel bridge then.

**Comment by Seeburschbanause** [comment]
> Tried in test mode already but didn't work. Seem like we have to wait for new kernel bridge then.

Worked for me. Used these guides from the MS Docs:

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/creating-test-certificates

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/test-signing-a-driver-through-an-embedded-signature

However the program can't seem to find a valid keyslot table.

**Comment by billyhulbert** [comment]
> 
Which version of the GamingServices do you have installed on your machine/instance? Is it possible the version isn't supported in the current version of the utility?

**Comment by Seeburschbanause** [comment]
> > 
> 
> Which version of the GamingServices do you have installed on your machine/instance? Is it possible the version isn't supported in the current version of the utility?

Current driver version is 10.0.22000.2338. Looks like the utility needs an update.

**Comment by billyhulbert** [comment]
I can confirm that after enabling test mode and test signing the Kernel-Bridge driver that I had success. I went ahead and quickly updated for the latest GamingServices version. The current code needs to be updated when reading from the XVDD memory space.

**Comment by Seeburschbanause** [comment]
Works perfectly now. Had to change the dump size a bit though.

**Comment by Umaroth8419** [comment]
I'm also having an issue locating a keytable. It appears that Gaming Services has updated again. Would that have anything to do with why I can't locate a keytable?

**Comment by billyhulbert** [comment]
The most likely reason is due to the dump size not being large enough. I've been spending little time looking into it to hopefully find an appropriate way of determining the current size. I tried looking at SizeOfImage and more but nothing seems to be of use.

Perhaps just do it in an increment of some value until possibly finding something before failing? We'll see.
